CREATE SCHEMA operations;

GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA operations TO developer;
GRANT ALL PRIVILEGES ON ALL SEQUENCES IN SCHEMA operations TO developer;
GRANT ALL PRIVILEGES ON SCHEMA operations TO developer;

ALTER DEFAULT PRIVILEGES IN SCHEMA operations GRANT ALL ON TABLES TO developer;
ALTER DEFAULT PRIVILEGES FOR ROLE developer IN SCHEMA operations GRANT ALL ON TABLES TO developer;
ALGER DEFAULT PRIVILEGES FOR ROLE developer IN SCHEMA operations GRANT ALL ON SEQUENCES TO developer;